/**
 * @license
 * lodash 3.10.1 (Custom Build) lodash.com/license | Underscore.js 1.8.3 underscorejs.org/LICENSE
 * Build: `lodash include="throttle"`
 */
;(function(){function t(){}function e(t,e,n){function i(e,n){n&&clearTimeout(n),p=g=m=r,e&&(w=j(),s=t.apply(d,l),g||p||(l=d=r))}function u(){var t=e-(j()-y);0>=t||t>e?i(m,p):g=setTimeout(u,t)}function a(){i(h,g)}function f(){if(l=arguments,y=j(),d=this,m=h&&(g||!x),false===T)var n=x&&!g;else{p||x||(w=y);var o=T-(y-w),i=0>=o||o>T;i?(p&&(p=clearTimeout(p)),w=y,s=t.apply(d,l)):p||(p=setTimeout(a,o))}return i&&g?g=clearTimeout(g):g||e===T||(g=setTimeout(u,e)),n&&(i=true,s=t.apply(d,l)),!i||g||p||(l=d=r),s}
var l,p,s,y,d,g,m,w=0,T=false,h=true;if(typeof t!="function")throw new TypeError(c);if(e=0>e?0:+e||0,true===n)var x=true,h=false;else o(n)&&(x=!!n.leading,T="maxWait"in n&&b(+n.maxWait||0,e),h="trailing"in n?!!n.trailing:h);return f.cancel=function(){g&&clearTimeout(g),p&&clearTimeout(p),w=0,p=g=m=r},f}function n(t){return o(t)&&m.call(t)==u}function o(t){var e=typeof t;return!!t&&("object"==e||"function"==e)}function i(t){return null==t?false:n(t)?w.test(g.call(t)):!!t&&typeof t=="object"&&(d(t)?w:a).test(t)}var r,c="Expected a function",u="[object Function]",a=/^\[object .+?Constructor\]$/,f={
"function":true,object:true},l=f[typeof exports]&&exports&&!exports.nodeType&&exports,p=f[typeof module]&&module&&!module.nodeType&&module,s=f[typeof self]&&self&&self.Object&&self,y=f[typeof window]&&window&&window.Object&&window,f=p&&p.exports===l&&l,s=l&&p&&typeof global=="object"&&global&&global.Object&&global||y!==(this&&this.window)&&y||s||this,d=function(){try{Object({toString:0}+"")}catch(t){return function(){return false}}return function(t){return typeof t.toString!="function"&&typeof(t+"")=="string";
}}(),y=Object.prototype,g=Function.prototype.toString,m=y.toString,w=RegExp("^"+g.call(y.hasOwnProperty).replace(/[\\^$.*+?()[\]{}|]/g,"\\$&").replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g,"$1.*?")+"$"),b=Math.max,j=function(t,e){var n=null==t?r:t[e];return i(n)?n:r}(Date,"now")||function(){return(new Date).getTime()};t.debounce=e,t.throttle=function(t,n,i){var r=true,u=true;if(typeof t!="function")throw new TypeError(c);return false===i?r=false:o(i)&&(r="leading"in i?!!i.leading:r,u="trailing"in i?!!i.trailing:u),
e(t,n,{leading:r,maxWait:+n,trailing:u})},t.isFunction=n,t.isNative=i,t.isObject=o,t.now=j,t.VERSION="3.10.1",typeof define=="function"&&typeof define.amd=="object"&&define.amd?(s._=t, define(function(){return t})):l&&p?f?(p.exports=t)._=t:l._=t:s._=t}).call(this);